"""Public protocol contracts for OneSearch remote indexing agents."""

from .protocol import (
    PROTOCOL_VERSION,
    AgentEnrollmentRequest,
    AgentEnrollmentResponse,
    AgentHeartbeat,
    AgentJobLease,
    AllowedRoot,
    BatchAck,
    BrowseRequest,
    BrowseResponse,
    DirectoryEntry,
    DocumentBatch,
    JobCompletion,
    JobFailureReason,
    JobKind,
    JobProgress,
    JobStatus,
    NormalizedRemoteDocument,
    ProcessingMode,
    ProtocolCompatibilityResponse,
    ProtocolVersionRange,
    ScanCheckpoint,
    ScanFailure,
    ScanFile,
    ScanManifest,
    WireModel,
)

__all__ = [
    "PROTOCOL_VERSION",
    "AgentEnrollmentRequest",
    "AgentEnrollmentResponse",
    "AgentHeartbeat",
    "AgentJobLease",
    "AllowedRoot",
    "BatchAck",
    "BrowseRequest",
    "BrowseResponse",
    "DirectoryEntry",
    "DocumentBatch",
    "JobCompletion",
    "JobFailureReason",
    "JobKind",
    "JobProgress",
    "JobStatus",
    "NormalizedRemoteDocument",
    "ProcessingMode",
    "ProtocolCompatibilityResponse",
    "ProtocolVersionRange",
    "ScanCheckpoint",
    "ScanFile",
    "ScanFailure",
    "ScanManifest",
    "WireModel",
]
