"""Initial schema - sources and indexed_files tables

Revision ID: 7de02f6a9de2
Revises: 
Create Date: 2025-12-07 00:54:42.104997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de02f6a9de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('include_patterns', sa.Text(), nullable=True),
    sa.Column('exclude_patterns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_id'), ['id'], unique=False)

    op.create_table('indexed_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indexed_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indexed_files_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_indexed_files_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexed_files_source_id'))
        batch_op.drop_index(batch_op.f('ix_indexed_files_path'))

    op.drop_table('indexed_files')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_id'))

    op.drop_table('sources')
    # ### end Alembic commands ###
