# Copyright (C) 2025 demigodmode
# SPDX-License-Identifier: AGPL-3.0-only

"""add schedule fields to sources

Revision ID: d58d802ad43e
Revises: b72305870c4f
Create Date: 2026-02-05 15:38:24.436240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58d802ad43e'
down_revision = 'b72305870c4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_schedule', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_scan_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_scan_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('next_scan_at')
        batch_op.drop_column('last_scan_at')
        batch_op.drop_column('scan_schedule')

    # ### end Alembic commands ###
