import { Button } from '@/components/ui/button'
import type { AgentDetails as AgentDetailsModel, ProcessingMode } from '@/types/api'

export function AgentDetails({ agent, onClose, onDisable, onRevoke, onMode }: { agent: AgentDetailsModel; onClose: () => void; onDisable: () => void; onRevoke: () => void; onMode: (mode: ProcessingMode) => void }) {
  return <section className="rounded-lg border border-border bg-card p-4 space-y-4" aria-label={`${agent.name} details`}><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{agent.name}</h2><p className="text-sm text-muted-foreground">{agent.platform} · v{agent.version} · protocol {agent.protocol_version} · last contact {agent.last_seen_at ? new Date(agent.last_seen_at).toLocaleString() : 'never'}</p></div><Button size="sm" variant="ghost" onClick={onClose}>Close</Button></div>
    <div className="grid gap-3 sm:grid-cols-2"><div><h3 className="text-sm font-medium">Allowed roots</h3><ul className="text-sm text-muted-foreground">{agent.allowed_roots.map((root) => <li key={root.root_id}>{root.path}</li>)}</ul></div><div><h3 className="text-sm font-medium">Attached sources</h3><ul className="text-sm text-muted-foreground">{agent.sources.map((source) => <li key={source.id}>{source.name}: {source.root_path}</li>) || 'None'}</ul></div></div>
    <label className="block text-sm">Default processing mode<select value={agent.default_processing_mode} onChange={(event) => onMode(event.target.value as ProcessingMode)} className="mt-1 block rounded-lg border border-border bg-background px-2 py-1"><option value="on_agent">On agent</option><option value="on_server">On server</option></select></label>
    <p className="text-sm text-muted-foreground">Auto-update: {agent.auto_update ? 'enabled' : 'not configured'}.</p>
    <div><h3 className="text-sm font-medium">Recent jobs</h3>{agent.recent_jobs.length ? <ul className="mt-1 space-y-1 text-sm text-muted-foreground">{agent.recent_jobs.map((job) => <li key={job.id}>{job.kind} · {job.status}{job.error ? ` — ${job.error}` : ''}</li>)}</ul> : <p className="text-sm text-muted-foreground">No recent jobs.</p>}</div>
    {agent.status !== 'revoked' && <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={onDisable}>Disable credential</Button><Button size="sm" variant="destructive" onClick={onRevoke}>Revoke credential</Button></div>}
  </section>
}
